name: Blazor WASM Example Page

on:
  push:
    branches: [ main ]

jobs:
  build-github-page:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET5 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
    
      - name: Publish .NET Core Project
        run: dotnet publish src/GumihoUI/ExamplesWASM/ExamplesWASM.csproj -c Release -o release --nologo
          
      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/gumiho-ui\/" \/>/g' release/wwwroot/index.html
        
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll
        
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
        


